### ISSUE TITLE
Enhance docs with regards to prereqs

### ISSUE THREAD

**Issue by paxtonhare** [rjrudin/slush-marklogic-spring-boot#15]
I just ran through the setup on a windows box. I suggest updating the pre-reqs to list out the following:

Jdk (vs jre)
Gradle
Node 4.x+
Gulp
Bower
Slush
Git <= Needed for Bower to run

**Comment by paxtonhare** [comment]
I was starting with a naked windows install. I had accidentally loaded the JRE. But I think it's worth noting in the docs that all these things need be installed. Otherwise stuff starts failing along the way.

**Comment by rjrudin** [comment]
@paxtonhare How does this look - https://github.com/rjrudin/slush-marklogic-spring-boot/tree/dev ?

**Comment by paxtonhare** [comment]
Looks fantastic!
