### ISSUE TITLE
Unable to override Gradle properties via command line

### ISSUE THREAD

**Issue by rjrudin** [rjrudin/slush-marklogic-spring-boot#16]
The way properties are read in from application.properties is superceding the command line, which is no good.

**Comment by patrickmcelwee** [comment]
It would be nice to be able to override properties with a `local.properties` file - so you can have developer-level configuration. I couldn't find an existing way to do it. Would you be open to me trying to add that?

**Comment by patrickmcelwee** [comment]
Also, if I override mlRestPort on the command line during both mlDeploy and bootRun, I still apparently run into a problem (possibly in [DevConfig.java](https://github.com/rjrudin/slush-marklogic-spring-boot/blob/master/templates/src/main/java/org/example/DevConfig.java#L27)?) where the hard-coded version in application.properties reasserts itself

**Comment by rjrudin** [comment]
I believe this is considered to be the best way to manage properties for different environments in Gradle - https://github.com/stevesaliman/gradle-properties-plugin . I recommend giving that a try - I've been reluctant to address this within ml-gradle because I feel like I'd be reinventing the wheel a bit.

**Comment by patrickmcelwee** [comment]
thanks ... I'll take a look at that

**Comment by rjrudin** [comment]
To affect bootRun, I believe you'll need to use "-D". 

"-P" is Gradle's way of overriding Gradle properties, such as those read in from src/main/resources/application.properties. But when you run bootRun, the values in application.properties are read in by Spring. And Spring will override those based on environment variables, which are set in a JVM via "-D".

Actually... I think you have to make sure that any "-D" variables are passed to the JVM that bootRun launches. I just did a quick search, and this looks like the easiest way to do that: http://stackoverflow.com/a/31328621/3306099
