### ISSUE TITLE
Download.xsl not found

### ISSUE THREAD

**Issue by sastafford** [rjrudin/slush-marklogic-spring-boot#24]
I'm seeing this warning in the Spring Boot log files

12:34:51.479 [pool-1-thread-1] WARN  c.m.c.m.i.DefaultExtensionMetadataProvider - Unable to build metadata from resource file: file:/home/sstafford/grey/src/main/ml-modules/transforms/download.xsl; cause: /home/sstafford/grey/src/main/ml-modules/transforms/metadata/download.xml (No such file or directory)

**Comment by rjrudin** [comment]
Is that with 0.4.0 or 0.3.0 of a slush-generated app?

This is fixed in the latest version of ml-javaclient-util - by "fixed", I mean that it's logged at the debug level instead of warn, because it's not an issue at all.

**Comment by rjrudin** [comment]
If you upgrade ml-javaclient-util to 2.9.0-RC1 or 2.9.0 in build.gradle, the warning will go away. This is addressed in 0.4.0 of SMSB.
