### ISSUE TITLE
Package as WAR for deployment 

### ISSUE THREAD

**Issue by Brian-z** [rjrudin/slush-marklogic-spring-boot#50]
Hi All,

I have been struggling to learn how to turn this into a WAR file for dedicated deployment. I have tried using the build files, but it appears that the structure that is output is not valid. Is there an way to convert this into a WAR file / webapp directory structure.

**Comment by rjrudin** [comment]
I haven't looked into how spring boot allows this in a long time. Check the spring boot docs to see what the latest guidance is for doing this. There isn't anything unusual about this project that should prevent a war file from being created if spring boot allows that to be done.

**Comment by ralmodiel** [comment]
Hi @Brian-z ,

Check out this branch and the commit - instructions are in the readme file:
[gradle-cargo-plugin branch](https://github.com/ralmodiel/slush-marklogic-spring-boot/commit/7d7e69ea0f947686aec611e539514f0a1377f43b)

Gradle part was quick but took time to to change all links and rest url to relative paths to allow non-root context on deployments.

So far tests show war generated may now be deployed to a Tomcat while keeping the original embedded Tomcat for bootRun or 'java -jar one.jar' options intact.  Added the gradle cargo plugin also to simplify deployment to other application servers like WebLogic, WebSphere, etc.

Test it out for spin, I think I still need to test it further before making a pull request.

**Comment by Brian-z** [comment]
Hi @ralmodiel Thank you for that sample. That should be good to get me started in the right direction. Thanks again for the post.
