### ISSUE TITLE
Error during mlDeploy

### ISSUE THREAD

**Issue by rjkennedy98** [rjrudin/slush-marklogic-spring-boot#54]
I did a clean install of the slush-marklogic-spring-boot and I am getting an error.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':mlDeployApp'.
...
Caused by: org.jaxen.UnresolvableException: Function :local-name

I am using Windows 7 and ML 9.0-3.

**Comment by ralmodiel** [comment]
Hi Richard,

We got some significant updates for this project and will be releasing a
new version soon.  Kindly check this branch /release/v1.0.0-alpha
<https://github.com/rjrudin/slush-marklogic-spring-boot/tree/release/v1.0.0-alpha>

Regards,
Roque

**Comment by sparnell** [comment]
I see this is still open, so I thought I'd add this. The issue (not documented here, but mentioned in the README.md dropped by slush) is that you're required to create a gradle wrapper specifying some 2.x version of gradle for it to work. I'm using gradle 4.7, but created a wrapper using 2.14.1 and it works as expected.

**Comment by rjrudin** [comment]
Thanks @sparnell I should have closed this awhile ago - yes, the requirement is to use Gradle 2.x, it's noted in the docs too.
